// Country configuration registry. One entry per live country subdirectory.
// Used by <RegionNavbar>, <RegionFooter>, <RegionMobileNav>, and page metadata.
// Adding a new country:
//   1. Add an entry here
//   2. Create pages in src/app/[cc]/
//   3. Add sitemap + redirect entries in sitemap.ts / next.config.mjs
//
// Do NOT include "us" or "ca" here — those keep their legacy dedicated components
// (us-footer.tsx, sticky-navbar.tsx, ca-footer.tsx, ca-navbar.tsx) for zero regression risk.

export interface CountryNavService {
  label: string;
  href: string;
}

export interface CountryConfig {
  cc: string;                       // "mx", "br", ...
  countryName: string;              // "Mexico"
  countryNameLocative: string;      // "Mexico" for "in Mexico"
  hreflang: string;                 // "en-MX"
  dialCodeCountryIso2: string;      // "MX" (used as contact form default)

  // URL layout (differs per country)
  servicesIndexPath: string;        // "/mx/service/"
  serviceDetailPattern: string;     // "/mx/{slug}/" or "/mx/services/{slug}/"
  blogIndexPath: string;            // "/mx/blogs/" or "/mx/blog/" or "/mx/our-blogs/"
  blogDetailPattern: string;        // "/mx/{slug}/" or "/mx/blog/{slug}/"
  aboutPath: string;                // "/mx/about-us/"
  contactPath: string;              // "/mx/contact-us/"
  caseStudyPath: string | null;     // "/mx/case-study/" or null

  // Footer / contact
  address: string;                  // "Mexico City, Mexico"
  phone: string;                    // "+52 (800) 000-0000"
  email: string;                    // "info@carelabz.com"
  footerDescription: string;        // full sentence

  // Services shown in nav dropdown + footer (label + relative href)
  services: CountryNavService[];

  // Local electrical standards (used in Strapi seoKeywords, trust badges, etc.)
  standards: string[];              // ["NOM-029-STPS-2011", "IEEE 1584", ...]
  primaryStandard: string;          // "NOM-029-STPS-2011"
  localCodeName: string;            // "Mexican Electrical Code (NOM-001-SEDE)"
  localAuthority: string;           // "STPS"
}

// Helper to build standard service list from slugs
function defaultServices(cc: string, pattern: (slug: string) => string): CountryNavService[] {
  return [
    { label: "Arc Flash Study", href: pattern("arc-flash-study") },
    { label: "Short Circuit Analysis", href: pattern("short-circuit-analysis") },
    { label: "Load Flow Analysis", href: pattern("load-flow-analysis") },
    { label: "Relay Coordination Study", href: pattern("relay-coordination-study") },
  ];
}

export const COUNTRY_CONFIGS: Record<string, CountryConfig> = {
  mx: {
    cc: "mx",
    countryName: "Mexico",
    countryNameLocative: "Mexico",
    hreflang: "en-MX",
    dialCodeCountryIso2: "MX",
    servicesIndexPath: "/mx/service/",
    serviceDetailPattern: "/mx/{slug}/",
    blogIndexPath: "/mx/blogs/",
    blogDetailPattern: "/mx/{slug}/",
    aboutPath: "/mx/about-us/",
    contactPath: "/mx/contact-us/",
    caseStudyPath: null,
    address: "Mexico City, Mexico",
    phone: "+52 (55) 0000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers NOM-029 arc flash studies, NOM-001-SEDE compliance, and full power system engineering services across Mexico.",
    services: defaultServices("mx", (s) => `/mx/${s}/`),
    standards: [
      "NOM-029-STPS-2011",
      "NOM-001-SEDE",
      "IEEE 1584",
      "IEC 60909",
      "ETAP",
      "NFPA 70E",
    ],
    primaryStandard: "NOM-029-STPS-2011",
    localCodeName: "Mexican Electrical Code (NOM-001-SEDE)",
    localAuthority: "STPS (Secretaría del Trabajo)",
  },
  eg: {
    cc: "eg", countryName: "Egypt", countryNameLocative: "Egypt",
    hreflang: "en-EG", dialCodeCountryIso2: "EG",
    servicesIndexPath: "/eg/our-services/", serviceDetailPattern: "/eg/{slug}/",
    blogIndexPath: "/eg/blogs/", blogDetailPattern: "/eg/{slug}/",
    aboutPath: "/eg/about-us/", contactPath: "/eg/contact-us/", caseStudyPath: null,
    address: "Cairo, Egypt", phone: "+20 00 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers ECP arc flash studies, Ministry of Electricity-aligned compliance, and full power system engineering services across Egypt.",
    services: [
      { label: "Arc Flash Study", href: "/eg/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/eg/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/eg/motor-start-analysis/" },
      { label: "Power System Study", href: "/eg/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/eg/power-quality-analysis/" },
    ],
    standards: ["Egyptian Code for Electrical Installations (ECP)", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "Egyptian Code for Electrical Installations (ECP)",
    localCodeName: "ECP (Egyptian Code for Electrical Installations)",
    localAuthority: "Ministry of Electricity and Renewable Energy",
  },
  za: {
    cc: "za", countryName: "South Africa", countryNameLocative: "South Africa",
    hreflang: "en-ZA", dialCodeCountryIso2: "ZA",
    servicesIndexPath: "/za/our-services/", serviceDetailPattern: "/za/{slug}/",
    blogIndexPath: "/za/blogs/", blogDetailPattern: "/za/{slug}/",
    aboutPath: "/za/about-us/", contactPath: "/za/contact-us/", caseStudyPath: null,
    address: "Johannesburg, South Africa", phone: "+27 00 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers SANS 10142 arc flash studies, DMRE-aligned compliance, and full power system engineering services across South Africa.",
    services: [
      { label: "Arc Flash Study", href: "/za/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/za/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/za/motor-start-analysis/" },
      { label: "Power System Study", href: "/za/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/za/power-quality-analysis/" },
    ],
    standards: ["SANS 10142", "OHS Act", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "SANS 10142",
    localCodeName: "SANS 10142 (South African Wiring Code)",
    localAuthority: "DMRE",
  },
  tr: {
    cc: "tr", countryName: "Turkey", countryNameLocative: "Turkey",
    hreflang: "en-TR", dialCodeCountryIso2: "TR",
    servicesIndexPath: "/tr/our-services/", serviceDetailPattern: "/tr/{slug}/",
    blogIndexPath: "/tr/blogs/", blogDetailPattern: "/tr/{slug}/",
    aboutPath: "/tr/about-us/", contactPath: "/tr/contact-us/", caseStudyPath: null,
    address: "Istanbul, Turkey", phone: "+90 000 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers TS HD 60364 arc flash studies, CSGB-aligned compliance, and full power system engineering services across Turkey.",
    services: [
      { label: "Arc Flash Study", href: "/tr/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/tr/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/tr/motor-start-analysis/" },
      { label: "Power System Study", href: "/tr/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/tr/power-quality-analysis/" },
    ],
    standards: ["TS HD 60364", "İç Tesisler Yönetmeliği", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "TS HD 60364",
    localCodeName: "TS HD 60364 (Turkish Electrical Installation Standard)",
    localAuthority: "ÇSGB",
  },
  sa: {
    cc: "sa", countryName: "Saudi Arabia", countryNameLocative: "Saudi Arabia",
    hreflang: "en-SA", dialCodeCountryIso2: "SA",
    servicesIndexPath: "/sa/our-services/", serviceDetailPattern: "/sa/{slug}/",
    blogIndexPath: "/sa/blogs/", blogDetailPattern: "/sa/{slug}/",
    aboutPath: "/sa/about-us/", contactPath: "/sa/contact-us/", caseStudyPath: null,
    address: "Riyadh, Saudi Arabia", phone: "+966 0 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers SBC 401 arc flash studies, HCIS-aligned compliance, and full power system engineering services across Saudi Arabia.",
    services: [
      { label: "Arc Flash Study", href: "/sa/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/sa/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/sa/motor-start-analysis/" },
      { label: "Power System Study", href: "/sa/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/sa/power-quality-analysis/" },
    ],
    standards: ["SBC 401", "SASO IEC 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "SBC 401",
    localCodeName: "SBC 401 (Saudi Building Code — Electrical)",
    localAuthority: "HCIS",
  },
  nz: {
    cc: "nz", countryName: "New Zealand", countryNameLocative: "New Zealand",
    hreflang: "en-NZ", dialCodeCountryIso2: "NZ",
    servicesIndexPath: "/nz/our-services/", serviceDetailPattern: "/nz/{slug}/",
    blogIndexPath: "/nz/blogs/", blogDetailPattern: "/nz/{slug}/",
    aboutPath: "/nz/about-us/", contactPath: "/nz/contact-us/", caseStudyPath: null,
    address: "Auckland, New Zealand", phone: "+64 0 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers AS/NZS 3000 arc flash studies, WorkSafe NZ-aligned compliance, and full power system engineering services across New Zealand.",
    services: [
      { label: "Arc Flash Study", href: "/nz/arc-flash-study-in-new-zealand/" },
      { label: "Harmonic Study", href: "/nz/harmonic-study-in-new-zealand/" },
      { label: "Motor Start Analysis", href: "/nz/motor-start-analysis-in-new-zealand/" },
      { label: "Power System Study", href: "/nz/power-system-study-in-new-zealand/" },
      { label: "Power Quality Analysis", href: "/nz/power-quality-analysis-in-new-zealand/" },
    ],
    standards: ["AS/NZS 3000", "AS/NZS 3012", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "AS/NZS 3000",
    localCodeName: "AS/NZS 3000 (Wiring Rules)",
    localAuthority: "WorkSafe New Zealand",
  },
  au: {
    cc: "au", countryName: "Australia", countryNameLocative: "Australia",
    hreflang: "en-AU", dialCodeCountryIso2: "AU",
    servicesIndexPath: "/au/our-services/", serviceDetailPattern: "/au/{slug}/",
    blogIndexPath: "/au/blog/", blogDetailPattern: "/au/{slug}/",
    aboutPath: "/au/about-us/", contactPath: "/au/contact-us/", caseStudyPath: null,
    address: "Sydney, Australia", phone: "+61 0 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers AS/NZS 3000 arc flash studies, Safe Work Australia-aligned compliance, and full power system engineering services across Australia.",
    services: [
      { label: "Arc Flash Study", href: "/au/arc-flash-study-in-australia/" },
      { label: "Short Circuit Analysis", href: "/au/short-circuit-analysis-in-australia/" },
      { label: "Load Flow Analysis", href: "/au/load-flow-analysis-in-australia/" },
      { label: "Relay Coordination Study", href: "/au/relay-coordination-study-services-in-australia/" },
    ],
    standards: ["AS/NZS 3000", "AS/NZS 3012", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "AS/NZS 3000",
    localCodeName: "AS/NZS 3000 (Australian/New Zealand Wiring Rules)",
    localAuthority: "Safe Work Australia",
  },
  ph: {
    cc: "ph", countryName: "Philippines", countryNameLocative: "the Philippines",
    hreflang: "en-PH", dialCodeCountryIso2: "PH",
    servicesIndexPath: "/ph/our-services/", serviceDetailPattern: "/ph/{slug}/",
    blogIndexPath: "/ph/blogs/", blogDetailPattern: "/ph/{slug}/",
    aboutPath: "/ph/about-us/", contactPath: "/ph/contact-us/", caseStudyPath: null,
    address: "Manila, Philippines", phone: "+63 0 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers Philippine Electrical Code arc flash studies, DOLE-aligned compliance, and full power system engineering services across the Philippines.",
    services: [
      { label: "Arc Flash Study", href: "/ph/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/ph/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/ph/motor-start-analysis/" },
      { label: "Power System Study", href: "/ph/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/ph/power-quality-analysis/" },
    ],
    standards: ["Philippine Electrical Code", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "Philippine Electrical Code",
    localCodeName: "PEC (Philippine Electrical Code)",
    localAuthority: "DOLE",
  },
  id: {
    cc: "id", countryName: "Indonesia", countryNameLocative: "Indonesia",
    hreflang: "en-ID", dialCodeCountryIso2: "ID",
    servicesIndexPath: "/id/our-services/", serviceDetailPattern: "/id/{slug}/",
    blogIndexPath: "/id/blogs/", blogDetailPattern: "/id/{slug}/",
    aboutPath: "/id/about-us/", contactPath: "/id/contact-us/", caseStudyPath: null,
    address: "Jakarta, Indonesia", phone: "+62 00 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers PUIL 2011 arc flash studies, ESDM-aligned compliance, and full power system engineering services across Indonesia.",
    services: [
      { label: "Arc Flash Study", href: "/id/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/id/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/id/motor-start-analysis/" },
      { label: "Power System Study", href: "/id/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/id/power-quality-analysis/" },
    ],
    standards: ["PUIL 2011", "SNI IEC 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "PUIL 2011",
    localCodeName: "PUIL 2011 (Indonesian Electrical Installation Standard)",
    localAuthority: "Kementerian ESDM",
  },
  vn: {
    cc: "vn", countryName: "Vietnam", countryNameLocative: "Vietnam",
    hreflang: "en-VN", dialCodeCountryIso2: "VN",
    servicesIndexPath: "/vn/our-services/", serviceDetailPattern: "/vn/{slug}/",
    blogIndexPath: "/vn/blogs/", blogDetailPattern: "/vn/{slug}/",
    aboutPath: "/vn/about-us/", contactPath: "/vn/contact-us/", caseStudyPath: null,
    address: "Ho Chi Minh City, Vietnam", phone: "+84 00 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers TCVN 7447 arc flash studies, DOLISA-aligned compliance, and full power system engineering services across Vietnam.",
    services: [
      { label: "Arc Flash Study", href: "/vn/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/vn/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/vn/motor-start-analysis/" },
      { label: "Power System Study", href: "/vn/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/vn/power-quality-analysis/" },
    ],
    standards: ["TCVN 7447", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "TCVN 7447",
    localCodeName: "TCVN 7447 (Vietnamese Electrical Installation Standard)",
    localAuthority: "DOLISA",
  },
  th: {
    cc: "th", countryName: "Thailand", countryNameLocative: "Thailand",
    hreflang: "en-TH", dialCodeCountryIso2: "TH",
    servicesIndexPath: "/th/our-services/", serviceDetailPattern: "/th/{slug}/",
    blogIndexPath: "/th/blogs/", blogDetailPattern: "/th/{slug}/",
    aboutPath: "/th/about-us/", contactPath: "/th/contact-us/", caseStudyPath: null,
    address: "Bangkok, Thailand", phone: "+66 0 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers EIT Standard arc flash studies, DOE-aligned compliance, and full power system engineering services across Thailand.",
    services: [
      { label: "Arc Flash Study", href: "/th/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/th/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/th/motor-start-analysis/" },
      { label: "Power System Study", href: "/th/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/th/power-quality-analysis/" },
    ],
    standards: ["EIT Standard 2001-56", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "EIT Standard 2001-56",
    localCodeName: "EIT Standard for Electrical Installation",
    localAuthority: "DOE (Department of Energy)",
  },
  sg: {
    cc: "sg", countryName: "Singapore", countryNameLocative: "Singapore",
    hreflang: "en-SG", dialCodeCountryIso2: "SG",
    servicesIndexPath: "/sg/our-services/", serviceDetailPattern: "/sg/{slug}/",
    blogIndexPath: "/sg/blogs/", blogDetailPattern: "/sg/{slug}/",
    aboutPath: "/sg/about-us/", contactPath: "/sg/contact-us/", caseStudyPath: null,
    address: "Singapore", phone: "+65 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers SS 638 arc flash studies, EMA-aligned compliance, and full power system engineering services across Singapore.",
    services: [
      { label: "Arc Flash Study", href: "/sg/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/sg/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/sg/motor-start-analysis/" },
      { label: "Power System Study", href: "/sg/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/sg/power-quality-analysis/" },
    ],
    standards: ["SS 638", "CP5", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "SS 638",
    localCodeName: "SS 638 (Singapore Electrical Installation Standard)",
    localAuthority: "EMA",
  },
  my: {
    cc: "my", countryName: "Malaysia", countryNameLocative: "Malaysia",
    hreflang: "en-MY", dialCodeCountryIso2: "MY",
    servicesIndexPath: "/my/our-services/", serviceDetailPattern: "/my/{slug}/",
    blogIndexPath: "/my/blogs/", blogDetailPattern: "/my/{slug}/",
    aboutPath: "/my/about-us/", contactPath: "/my/contact-us/", caseStudyPath: null,
    address: "Kuala Lumpur, Malaysia", phone: "+60 0 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers MS IEC 60364 arc flash studies, DOSH-aligned compliance, and full power system engineering services across Malaysia.",
    services: [
      { label: "Arc Flash Study", href: "/my/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/my/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/my/motor-start-analysis/" },
      { label: "Power System Study", href: "/my/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/my/power-quality-analysis/" },
    ],
    standards: ["MS IEC 60364", "Electricity Regulations 1994", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "MS IEC 60364",
    localCodeName: "MS IEC 60364 (Malaysian Electrical Installation Standard)",
    localAuthority: "DOSH",
  },
  in: {
    cc: "in", countryName: "India", countryNameLocative: "India",
    hreflang: "en-IN", dialCodeCountryIso2: "IN",
    servicesIndexPath: "/in/our-services/", serviceDetailPattern: "/in/{slug}/",
    blogIndexPath: "/in/our-blogs/", blogDetailPattern: "/in/{slug}/",
    aboutPath: "/in/about-us/", contactPath: "/in/contact-us/", caseStudyPath: null,
    address: "Mumbai, India", phone: "+91 00 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers CEA Regulations arc flash studies, DGMS-aligned compliance, and full power system engineering services across India.",
    services: [
      { label: "Arc Flash Study", href: "/in/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/in/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/in/motor-start-analysis/" },
      { label: "Power System Study", href: "/in/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/in/power-quality-analysis/" },
    ],
    standards: ["CEA Regulations 2010", "IS 3043", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "CEA Regulations 2010",
    localCodeName: "CEA (Measures relating to Safety and Electric Supply) Regulations",
    localAuthority: "CEA / DGMS",
  },
  tw: {
    cc: "tw", countryName: "Taiwan", countryNameLocative: "Taiwan",
    hreflang: "en-TW", dialCodeCountryIso2: "TW",
    servicesIndexPath: "/tw/our-services/", serviceDetailPattern: "/tw/{slug}/",
    blogIndexPath: "/tw/blogs/", blogDetailPattern: "/tw/{slug}/",
    aboutPath: "/tw/about-us/", contactPath: "/tw/contact-us/", caseStudyPath: null,
    address: "Taipei, Taiwan", phone: "+886 0 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers Taiwan Electricity Supply Regulations arc flash studies, BSMI-aligned compliance, and full power system engineering services across Taiwan.",
    services: [
      { label: "Arc Flash Study", href: "/tw/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/tw/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/tw/motor-start-analysis/" },
      { label: "Power System Study", href: "/tw/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/tw/power-quality-analysis/" },
    ],
    standards: ["User Electricity Supply Regulations", "CNS 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "User Electricity Supply Regulations",
    localCodeName: "Taiwan User Electricity Supply Regulations",
    localAuthority: "BSMI",
  },
  hk: {
    cc: "hk", countryName: "Hong Kong", countryNameLocative: "Hong Kong",
    hreflang: "en-HK", dialCodeCountryIso2: "HK",
    servicesIndexPath: "/hk/our-services/", serviceDetailPattern: "/hk/{slug}/",
    blogIndexPath: "/hk/blogs/", blogDetailPattern: "/hk/{slug}/",
    aboutPath: "/hk/about-us/", contactPath: "/hk/contact-us/", caseStudyPath: null,
    address: "Hong Kong", phone: "+852 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers CoP arc flash studies, EMSD-aligned compliance, and full power system engineering services across Hong Kong.",
    services: [
      { label: "Arc Flash Study", href: "/hk/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/hk/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/hk/motor-start-analysis/" },
      { label: "Power System Study", href: "/hk/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/hk/power-quality-analysis/" },
    ],
    standards: ["CoP Electrical Installation", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "CoP Electrical Installation",
    localCodeName: "Code of Practice for the Electricity (Wiring) Regulations",
    localAuthority: "EMSD",
  },
  kr: {
    cc: "kr", countryName: "South Korea", countryNameLocative: "South Korea",
    hreflang: "en-KR", dialCodeCountryIso2: "KR",
    servicesIndexPath: "/kr/our-services/", serviceDetailPattern: "/kr/{slug}/",
    blogIndexPath: "/kr/blogs/", blogDetailPattern: "/kr/{slug}/",
    aboutPath: "/kr/about-us/", contactPath: "/kr/contact-us/", caseStudyPath: null,
    address: "Seoul, South Korea", phone: "+82 00 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers KEC arc flash studies, KISA-aligned compliance, and full power system engineering services across South Korea.",
    services: [
      { label: "Arc Flash Study", href: "/kr/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/kr/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/kr/motor-start-analysis/" },
      { label: "Power System Study", href: "/kr/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/kr/power-quality-analysis/" },
    ],
    standards: ["KEC", "KS C IEC 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "KEC",
    localCodeName: "KEC (Korea Electrotechnical Code)",
    localAuthority: "KISA",
  },
  jp: {
    cc: "jp", countryName: "Japan", countryNameLocative: "Japan",
    hreflang: "en-JP", dialCodeCountryIso2: "JP",
    servicesIndexPath: "/jp/our-services/", serviceDetailPattern: "/jp/{slug}/",
    blogIndexPath: "/jp/blogs/", blogDetailPattern: "/jp/{slug}/",
    aboutPath: "/jp/about-us/", contactPath: "/jp/contact-us/", caseStudyPath: null,
    address: "Tokyo, Japan", phone: "+81 00 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers JEAC 8001 arc flash studies, METI-aligned compliance, and full power system engineering services across Japan.",
    services: [
      { label: "Arc Flash Study", href: "/jp/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/jp/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/jp/motor-start-analysis/" },
      { label: "Power System Study", href: "/jp/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/jp/power-quality-analysis/" },
    ],
    standards: ["JEAC 8001", "JIS C 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "JEAC 8001",
    localCodeName: "JEAC 8001 (Japanese Electrical Installation Code)",
    localAuthority: "METI",
  },
  cn: {
    cc: "cn", countryName: "China", countryNameLocative: "China",
    hreflang: "en-CN", dialCodeCountryIso2: "CN",
    servicesIndexPath: "/cn/our-services/", serviceDetailPattern: "/cn/{slug}/",
    blogIndexPath: "/cn/blogs/", blogDetailPattern: "/cn/{slug}/",
    aboutPath: "/cn/about-us/", contactPath: "/cn/contact-us/", caseStudyPath: null,
    address: "Shanghai, China", phone: "+86 00 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers GB 50054 arc flash studies, SAC-aligned compliance, and full power system engineering services across China.",
    services: [
      { label: "Arc Flash Study", href: "/cn/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/cn/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/cn/motor-start-analysis/" },
      { label: "Power System Study", href: "/cn/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/cn/power-quality-analysis/" },
    ],
    standards: ["GB 50054", "GB 50303", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "GB 50054",
    localCodeName: "GB 50054 (Chinese Low-Voltage Distribution Design Standard)",
    localAuthority: "SAC",
  },
  ua: {
    cc: "ua", countryName: "Ukraine", countryNameLocative: "Ukraine",
    hreflang: "en-UA", dialCodeCountryIso2: "UA",
    servicesIndexPath: "/ua/our-services/", serviceDetailPattern: "/ua/{slug}/",
    blogIndexPath: "/ua/blogs/", blogDetailPattern: "/ua/{slug}/",
    aboutPath: "/ua/about-us/", contactPath: "/ua/contact-us/", caseStudyPath: null,
    address: "Kyiv, Ukraine", phone: "+380 00 000 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers PUE arc flash studies, Derzhpratsi-aligned compliance, and full power system engineering services across Ukraine.",
    services: [
      { label: "Arc Flash Study", href: "/ua/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/ua/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/ua/motor-start-analysis/" },
      { label: "Power System Study", href: "/ua/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/ua/power-quality-analysis/" },
    ],
    standards: ["PUE", "DBN V.2.5", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "PUE",
    localCodeName: "PUE / DBN V.2.5 (Ukrainian Electrical Installation Rules)",
    localAuthority: "Derzhpratsi",
  },
  sk: {
    cc: "sk", countryName: "Slovakia", countryNameLocative: "Slovakia",
    hreflang: "en-SK", dialCodeCountryIso2: "SK",
    servicesIndexPath: "/sk/our-services/", serviceDetailPattern: "/sk/{slug}/",
    blogIndexPath: "/sk/blogs/", blogDetailPattern: "/sk/{slug}/",
    aboutPath: "/sk/about-us/", contactPath: "/sk/contact-us/", caseStudyPath: null,
    address: "Bratislava, Slovakia", phone: "+421 00 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers STN 33 2000 arc flash studies, NIP-aligned compliance, and full power system engineering services across Slovakia.",
    services: [
      { label: "Arc Flash Study", href: "/sk/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/sk/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/sk/motor-start-analysis/" },
      { label: "Power System Study", href: "/sk/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/sk/power-quality-analysis/" },
    ],
    standards: ["STN 33 2000", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "STN 33 2000",
    localCodeName: "STN 33 2000 (Slovak Electrical Installation Standard)",
    localAuthority: "NIP",
  },
  ro: {
    cc: "ro", countryName: "Romania", countryNameLocative: "Romania",
    hreflang: "en-RO", dialCodeCountryIso2: "RO",
    servicesIndexPath: "/ro/our-services/", serviceDetailPattern: "/ro/{slug}/",
    blogIndexPath: "/ro/blogs/", blogDetailPattern: "/ro/{slug}/",
    aboutPath: "/ro/about-us/", contactPath: "/ro/contact-us/", caseStudyPath: null,
    address: "Bucharest, Romania", phone: "+40 000 000 000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers I7-2011 arc flash studies, IM-aligned compliance, and full power system engineering services across Romania.",
    services: [
      { label: "Arc Flash Study", href: "/ro/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/ro/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/ro/motor-start-analysis/" },
      { label: "Power System Study", href: "/ro/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/ro/power-quality-analysis/" },
    ],
    standards: ["I7-2011", "SR HD 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "I7-2011",
    localCodeName: "I7-2011 (Romanian Electrical Installation Standard)",
    localAuthority: "Inspectoratul Muncii",
  },
  cz: {
    cc: "cz", countryName: "Czech Republic", countryNameLocative: "Czech Republic",
    hreflang: "en-CZ", dialCodeCountryIso2: "CZ",
    servicesIndexPath: "/cz/our-services/", serviceDetailPattern: "/cz/{slug}/",
    blogIndexPath: "/cz/blogs/", blogDetailPattern: "/cz/{slug}/",
    aboutPath: "/cz/about-us/", contactPath: "/cz/contact-us/", caseStudyPath: null,
    address: "Prague, Czech Republic", phone: "+420 000 000 000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers ČSN 33 2000 arc flash studies, SÚIP-aligned compliance, and full power system engineering services across Czech Republic.",
    services: [
      { label: "Arc Flash Study", href: "/cz/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/cz/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/cz/motor-start-analysis/" },
      { label: "Power System Study", href: "/cz/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/cz/power-quality-analysis/" },
    ],
    standards: ["ČSN 33 2000", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "ČSN 33 2000",
    localCodeName: "ČSN 33 2000 (Czech Electrical Installation Standard)",
    localAuthority: "SÚIP",
  },
  hu: {
    cc: "hu", countryName: "Hungary", countryNameLocative: "Hungary",
    hreflang: "en-HU", dialCodeCountryIso2: "HU",
    servicesIndexPath: "/hu/our-services/", serviceDetailPattern: "/hu/{slug}/",
    blogIndexPath: "/hu/blogs/", blogDetailPattern: "/hu/{slug}/",
    aboutPath: "/hu/about-us/", contactPath: "/hu/contact-us/", caseStudyPath: null,
    address: "Budapest, Hungary", phone: "+36 0 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers MSZ HD 60364 arc flash studies, local authority-aligned compliance, and full power system engineering services across Hungary.",
    services: [
      { label: "Arc Flash Study", href: "/hu/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/hu/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/hu/motor-start-analysis/" },
      { label: "Power System Study", href: "/hu/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/hu/power-quality-analysis/" },
    ],
    standards: ["MSZ HD 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "MSZ HD 60364",
    localCodeName: "MSZ HD 60364 (Hungarian Electrical Installation Standard)",
    localAuthority: "Hungarian Labour Inspectorate",
  },
  pl: {
    cc: "pl", countryName: "Poland", countryNameLocative: "Poland",
    hreflang: "en-PL", dialCodeCountryIso2: "PL",
    servicesIndexPath: "/pl/our-services/", serviceDetailPattern: "/pl/{slug}/",
    blogIndexPath: "/pl/blogs/", blogDetailPattern: "/pl/{slug}/",
    aboutPath: "/pl/about-us/", contactPath: "/pl/contact-us/", caseStudyPath: null,
    address: "Warsaw, Poland", phone: "+48 00 000 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers PN-HD 60364 arc flash studies, UDT-aligned compliance, and full power system engineering services across Poland.",
    services: [
      { label: "Arc Flash Study", href: "/pl/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/pl/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/pl/motor-start-analysis/" },
      { label: "Power System Study", href: "/pl/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/pl/power-quality-analysis/" },
    ],
    standards: ["PN-HD 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "PN-HD 60364",
    localCodeName: "PN-HD 60364 (Polish Electrical Installation Standard)",
    localAuthority: "UDT",
  },
  ru: {
    cc: "ru", countryName: "Russia", countryNameLocative: "Russia",
    hreflang: "en-RU", dialCodeCountryIso2: "RU",
    servicesIndexPath: "/ru/our-services/", serviceDetailPattern: "/ru/{slug}/",
    blogIndexPath: "/ru/blogs/", blogDetailPattern: "/ru/{slug}/",
    aboutPath: "/ru/about-us/", contactPath: "/ru/contact-us/", caseStudyPath: null,
    address: "Moscow, Russia", phone: "+7 000 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers PUE-7 arc flash studies, Rostekhnadzor-aligned compliance, and full power system engineering services across Russia.",
    services: [
      { label: "Arc Flash Study", href: "/ru/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/ru/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/ru/motor-start-analysis/" },
      { label: "Power System Study", href: "/ru/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/ru/power-quality-analysis/" },
    ],
    standards: ["PUE-7", "GOST R 50571", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "PUE-7",
    localCodeName: "PUE-7 (Russian Electrical Installation Rules)",
    localAuthority: "Rostekhnadzor",
  },
  at: {
    cc: "at", countryName: "Austria", countryNameLocative: "Austria",
    hreflang: "en-AT", dialCodeCountryIso2: "AT",
    servicesIndexPath: "/at/our-services/", serviceDetailPattern: "/at/{slug}/",
    blogIndexPath: "/at/blogs/", blogDetailPattern: "/at/{slug}/",
    aboutPath: "/at/about-us/", contactPath: "/at/contact-us/", caseStudyPath: null,
    address: "Vienna, Austria", phone: "+43 0 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers ÖVE/ÖNORM E 8001 arc flash studies, AUVA-aligned compliance, and full power system engineering services across Austria.",
    services: [
      { label: "Arc Flash Study", href: "/at/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/at/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/at/motor-start-analysis/" },
      { label: "Power System Study", href: "/at/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/at/power-quality-analysis/" },
    ],
    standards: ["ÖVE/ÖNORM E 8001", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "ÖVE/ÖNORM E 8001",
    localCodeName: "ÖVE/ÖNORM E 8001 (Austrian Electrical Installation Standard)",
    localAuthority: "AUVA",
  },
  ch: {
    cc: "ch", countryName: "Switzerland", countryNameLocative: "Switzerland",
    hreflang: "en-CH", dialCodeCountryIso2: "CH",
    servicesIndexPath: "/ch/our-services/", serviceDetailPattern: "/ch/{slug}/",
    blogIndexPath: "/ch/blogs/", blogDetailPattern: "/ch/{slug}/",
    aboutPath: "/ch/about-us/", contactPath: "/ch/contact-us/", caseStudyPath: null,
    address: "Zurich, Switzerland", phone: "+41 00 000 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers NIN arc flash studies, SUVA-aligned compliance, and full power system engineering services across Switzerland.",
    services: [
      { label: "Arc Flash Study", href: "/ch/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/ch/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/ch/motor-start-analysis/" },
      { label: "Power System Study", href: "/ch/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/ch/power-quality-analysis/" },
    ],
    standards: ["NIN (SEV 1000)", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "NIN (SEV 1000)",
    localCodeName: "NIN — Niederspannungs-Installationsnorm",
    localAuthority: "SUVA",
  },
  be: {
    cc: "be", countryName: "Belgium", countryNameLocative: "Belgium",
    hreflang: "en-BE", dialCodeCountryIso2: "BE",
    servicesIndexPath: "/be/our-services/", serviceDetailPattern: "/be/{slug}/",
    blogIndexPath: "/be/blogs/", blogDetailPattern: "/be/{slug}/",
    aboutPath: "/be/about-us/", contactPath: "/be/contact-us/", caseStudyPath: null,
    address: "Brussels, Belgium", phone: "+32 0 000 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers AREI/RGIE arc flash studies, FPS Economy-aligned compliance, and full power system engineering services across Belgium.",
    services: [
      { label: "Arc Flash Study", href: "/be/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/be/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/be/motor-start-analysis/" },
      { label: "Power System Study", href: "/be/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/be/power-quality-analysis/" },
    ],
    standards: ["AREI/RGIE", "NBN HD 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "AREI/RGIE",
    localCodeName: "AREI/RGIE (Belgian Electrical Installation Regulation)",
    localAuthority: "FPS Economy",
  },
  nl: {
    cc: "nl", countryName: "Netherlands", countryNameLocative: "the Netherlands",
    hreflang: "en-NL", dialCodeCountryIso2: "NL",
    servicesIndexPath: "/nl/our-services/", serviceDetailPattern: "/nl/{slug}/",
    blogIndexPath: "/nl/blogs/", blogDetailPattern: "/nl/{slug}/",
    aboutPath: "/nl/about-us/", contactPath: "/nl/contact-us/", caseStudyPath: null,
    address: "Amsterdam, Netherlands", phone: "+31 00 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers NEN 1010 arc flash studies, ISZW-aligned compliance, and full power system engineering services across the Netherlands.",
    services: [
      { label: "Arc Flash Study", href: "/nl/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/nl/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/nl/motor-start-analysis/" },
      { label: "Power System Study", href: "/nl/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/nl/power-quality-analysis/" },
    ],
    standards: ["NEN 1010", "NEN 3140", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "NEN 1010",
    localCodeName: "NEN 1010 (Dutch Electrical Installation Standard)",
    localAuthority: "ISZW",
  },
  de: {
    cc: "de", countryName: "Germany", countryNameLocative: "Germany",
    hreflang: "en-DE", dialCodeCountryIso2: "DE",
    servicesIndexPath: "/de/services/", serviceDetailPattern: "/de/services/{slug}/",
    blogIndexPath: "/de/blogs/", blogDetailPattern: "/de/{slug}/",
    aboutPath: "/de/about-us/", contactPath: "/de/contact-us/", caseStudyPath: null,
    address: "Berlin, Germany", phone: "+49 00 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers VDE 0100 arc flash studies, BAuA-aligned compliance, and full power system engineering services across Germany.",
    services: [
      { label: "Arc Flash Study", href: "/de/services/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/de/services/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/de/services/motor-start-analysis/" },
      { label: "Power System Study", href: "/de/services/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/de/services/power-quality-analysis/" },
    ],
    standards: ["DIN VDE 0100", "DIN VDE 0105", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "DIN VDE 0100",
    localCodeName: "DIN VDE 0100 (German Electrical Installation Standard)",
    localAuthority: "BAuA",
  },
  fr: {
    cc: "fr", countryName: "France", countryNameLocative: "France",
    hreflang: "en-FR", dialCodeCountryIso2: "FR",
    servicesIndexPath: "/fr/our-services/", serviceDetailPattern: "/fr/{slug}/",
    blogIndexPath: "/fr/blogs/", blogDetailPattern: "/fr/{slug}/",
    aboutPath: "/fr/about-us/", contactPath: "/fr/contact-us/", caseStudyPath: null,
    address: "Paris, France", phone: "+33 0 00 00 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers NF C 15-100 arc flash studies, INRS-aligned compliance, and full power system engineering services across France.",
    services: [
      { label: "Arc Flash Study", href: "/fr/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/fr/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/fr/motor-start-analysis/" },
      { label: "Power System Study", href: "/fr/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/fr/power-quality-analysis/" },
    ],
    standards: ["NF C 15-100", "NF C 18-510", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "NF C 15-100",
    localCodeName: "NF C 15-100 (French Electrical Installation Standard)",
    localAuthority: "INRS",
  },
  gr: {
    cc: "gr", countryName: "Greece", countryNameLocative: "Greece",
    hreflang: "en-GR", dialCodeCountryIso2: "GR",
    servicesIndexPath: "/gr/our-services/", serviceDetailPattern: "/gr/{slug}/",
    blogIndexPath: "/gr/blogs/", blogDetailPattern: "/gr/{slug}/",
    aboutPath: "/gr/about-us/", contactPath: "/gr/contact-us/", caseStudyPath: null,
    address: "Athens, Greece", phone: "+30 000 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers ELOT HD 384 arc flash studies, local authority-aligned compliance, and full power system engineering services across Greece.",
    services: [
      { label: "Arc Flash Study", href: "/gr/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/gr/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/gr/motor-start-analysis/" },
      { label: "Power System Study", href: "/gr/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/gr/power-quality-analysis/" },
    ],
    standards: ["ELOT HD 384", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "ELOT HD 384",
    localCodeName: "ELOT HD 384 (Greek Electrical Installation Standard)",
    localAuthority: "Ministry of Environment and Energy",
  },
  pt: {
    cc: "pt", countryName: "Portugal", countryNameLocative: "Portugal",
    hreflang: "en-PT", dialCodeCountryIso2: "PT",
    servicesIndexPath: "/pt/our-services/", serviceDetailPattern: "/pt/{slug}/",
    blogIndexPath: "/pt/blogs/", blogDetailPattern: "/pt/{slug}/",
    aboutPath: "/pt/about-us/", contactPath: "/pt/contact-us/", caseStudyPath: null,
    address: "Lisbon, Portugal", phone: "+351 000 000 000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers RTIEBT arc flash studies, ACT-aligned compliance, and full power system engineering services across Portugal.",
    services: [
      { label: "Arc Flash Study", href: "/pt/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/pt/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/pt/motor-start-analysis/" },
      { label: "Power System Study", href: "/pt/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/pt/power-quality-analysis/" },
    ],
    standards: ["RTIEBT", "NP HD 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "RTIEBT",
    localCodeName: "RTIEBT (Portuguese Electrical Installation Regulations)",
    localAuthority: "ACT",
  },
  es: {
    cc: "es", countryName: "Spain", countryNameLocative: "Spain",
    hreflang: "en-ES", dialCodeCountryIso2: "ES",
    servicesIndexPath: "/es/our-services/", serviceDetailPattern: "/es/{slug}/",
    blogIndexPath: "/es/blogs/", blogDetailPattern: "/es/{slug}/",
    aboutPath: "/es/about-us/", contactPath: "/es/contact-us/", caseStudyPath: null,
    address: "Madrid, Spain", phone: "+34 00 000 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers REBT arc flash studies, INSST-aligned compliance, and full power system engineering services across Spain.",
    services: [
      { label: "Arc Flash Study", href: "/es/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/es/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/es/motor-start-analysis/" },
      { label: "Power System Study", href: "/es/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/es/power-quality-analysis/" },
    ],
    standards: ["REBT", "RD 614/2001", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "REBT",
    localCodeName: "REBT (Reglamento Electrotécnico para Baja Tensión)",
    localAuthority: "INSST",
  },
  it: {
    cc: "it", countryName: "Italy", countryNameLocative: "Italy",
    hreflang: "en-IT", dialCodeCountryIso2: "IT",
    servicesIndexPath: "/it/our-services/", serviceDetailPattern: "/it/{slug}/",
    blogIndexPath: "/it/blogs/", blogDetailPattern: "/it/{slug}/",
    aboutPath: "/it/about-us/", contactPath: "/it/contact-us/", caseStudyPath: null,
    address: "Milan, Italy", phone: "+39 00 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers CEI 64-8 arc flash studies, INAIL-aligned compliance, and full power system engineering services across Italy.",
    services: [
      { label: "Arc Flash Study", href: "/it/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/it/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/it/motor-start-analysis/" },
      { label: "Power System Study", href: "/it/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/it/power-quality-analysis/" },
    ],
    standards: ["CEI 64-8", "D.Lgs 81/2008", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "CEI 64-8",
    localCodeName: "CEI 64-8 (Italian Electrical Installation Standard)",
    localAuthority: "INAIL",
  },
  fi: {
    cc: "fi", countryName: "Finland", countryNameLocative: "Finland",
    hreflang: "en-FI", dialCodeCountryIso2: "FI",
    servicesIndexPath: "/fi/our-services/", serviceDetailPattern: "/fi/{slug}/",
    blogIndexPath: "/fi/blogs/", blogDetailPattern: "/fi/{slug}/",
    aboutPath: "/fi/about-us/", contactPath: "/fi/contact-us/", caseStudyPath: "/fi/case-studies/",
    address: "Helsinki, Finland", phone: "+358 00 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers SFS 6000 arc flash studies, Tukes-aligned compliance, and full power system engineering services across Finland.",
    services: [
      { label: "Arc Flash Study", href: "/fi/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/fi/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/fi/motor-start-analysis/" },
      { label: "Power System Study", href: "/fi/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/fi/power-quality-analysis/" },
    ],
    standards: ["SFS 6000", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "SFS 6000",
    localCodeName: "SFS 6000 (Finnish Electrical Installation Standard)",
    localAuthority: "Tukes",
  },
  dk: {
    cc: "dk", countryName: "Denmark", countryNameLocative: "Denmark",
    hreflang: "en-DK", dialCodeCountryIso2: "DK",
    servicesIndexPath: "/dk/our-services/", serviceDetailPattern: "/dk/{slug}/",
    blogIndexPath: "/dk/blogs/", blogDetailPattern: "/dk/{slug}/",
    aboutPath: "/dk/about-us/", contactPath: "/dk/contact-us/", caseStudyPath: "/dk/case-studies/",
    address: "Copenhagen, Denmark", phone: "+45 00 00 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers DS/HD 60364 arc flash studies, Sikkerhedsstyrelsen compliance, and full power system engineering services across Denmark.",
    services: [
      { label: "Arc Flash Study", href: "/dk/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/dk/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/dk/motor-start-analysis/" },
      { label: "Power System Study", href: "/dk/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/dk/power-quality-analysis/" },
    ],
    standards: ["DS/HD 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "DS/HD 60364",
    localCodeName: "DS/HD 60364 (Danish Electrical Installation Standard)",
    localAuthority: "Sikkerhedsstyrelsen",
  },
  no: {
    cc: "no", countryName: "Norway", countryNameLocative: "Norway",
    hreflang: "en-NO", dialCodeCountryIso2: "NO",
    servicesIndexPath: "/no/our-services/", serviceDetailPattern: "/no/{slug}/",
    blogIndexPath: "/no/blogs/", blogDetailPattern: "/no/{slug}/",
    aboutPath: "/no/about-us/", contactPath: "/no/contact-us/", caseStudyPath: "/no/case-studies/",
    address: "Oslo, Norway", phone: "+47 000 00 000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers NEK 400 arc flash studies, DSB-aligned compliance, and full power system engineering services across Norway.",
    services: [
      { label: "Arc Flash Study", href: "/no/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/no/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/no/motor-start-analysis/" },
      { label: "Power System Study", href: "/no/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/no/power-quality-analysis/" },
    ],
    standards: ["NEK 400", "FEK", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "NEK 400",
    localCodeName: "NEK 400 (Norwegian Electrical Installation Standard)",
    localAuthority: "DSB (Direktoratet for samfunnssikkerhet)",
  },
  se: {
    cc: "se", countryName: "Sweden", countryNameLocative: "Sweden",
    hreflang: "en-SE", dialCodeCountryIso2: "SE",
    servicesIndexPath: "/se/our-services/", serviceDetailPattern: "/se/{slug}/",
    blogIndexPath: "/se/blogs/", blogDetailPattern: "/se/{slug}/",
    aboutPath: "/se/about-us/", contactPath: "/se/contact-us/", caseStudyPath: "/se/case-studies/",
    address: "Stockholm, Sweden", phone: "+46 (8) 000-0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers EBR-aligned arc flash studies, Elsäkerhetsverket-compliant power system engineering across Sweden.",
    services: [
      { label: "Arc Flash Study", href: "/se/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/se/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/se/motor-start-analysis/" },
      { label: "Power System Study", href: "/se/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/se/power-quality-analysis/" },
    ],
    standards: ["EBR 18:2017", "SS-EN 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "EBR 18:2017",
    localCodeName: "SS-EN 60364 (Swedish Electrical Installation Standard)",
    localAuthority: "Elsäkerhetsverket",
  },
  ie: {
    cc: "ie",
    countryName: "Ireland",
    countryNameLocative: "Ireland",
    hreflang: "en-IE",
    dialCodeCountryIso2: "IE",
    servicesIndexPath: "/ie/our-services/",
    serviceDetailPattern: "/ie/{slug}/",
    blogIndexPath: "/ie/blogs/",
    blogDetailPattern: "/ie/{slug}/",
    aboutPath: "/ie/about-us/",
    contactPath: "/ie/contact-us/",
    caseStudyPath: "/ie/case-studies/",
    address: "Dublin, Ireland",
    phone: "+353 (1) 000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers I.S. 10101 arc flash studies, HSA-aligned compliance, and full power system engineering services across Ireland.",
    services: [
      { label: "Arc Flash Study", href: "/ie/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/ie/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/ie/motor-start-analysis/" },
      { label: "Power System Study", href: "/ie/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/ie/power-quality-analysis/" },
    ],
    standards: ["I.S. 10101:2020", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "I.S. 10101:2020",
    localCodeName: "I.S. 10101 (Irish National Electrical Safety Standard)",
    localAuthority: "HSA (Health and Safety Authority)",
  },
  uk: {
    cc: "uk",
    countryName: "United Kingdom",
    countryNameLocative: "the UK",
    hreflang: "en-GB",
    dialCodeCountryIso2: "GB",
    servicesIndexPath: "/uk/our-services/",
    serviceDetailPattern: "/uk/{slug}/",
    blogIndexPath: "/uk/blogs/",
    blogDetailPattern: "/uk/{slug}/",
    aboutPath: "/uk/about-us/",
    contactPath: "/uk/contact-us/",
    caseStudyPath: "/uk/case-studies/",
    address: "London, United Kingdom",
    phone: "+44 (20) 0000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers BS 7671 arc flash studies, IET Wiring Regulations compliance, and full power system engineering services across the UK.",
    services: [
      { label: "Arc Flash Study", href: "/uk/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/uk/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/uk/motor-start-analysis/" },
      { label: "Power System Study", href: "/uk/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/uk/power-quality-analysis/" },
    ],
    standards: ["BS 7671", "IET Wiring Regulations", "HSR25", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "BS 7671",
    localCodeName: "BS 7671 / IET Wiring Regulations",
    localAuthority: "HSE (Health and Safety Executive)",
  },
  pe: {
    cc: "pe",
    countryName: "Peru",
    countryNameLocative: "Peru",
    hreflang: "en-PE",
    dialCodeCountryIso2: "PE",
    servicesIndexPath: "/pe/services/",
    serviceDetailPattern: "/pe/{slug}/",
    blogIndexPath: "/pe/blogs/",
    blogDetailPattern: "/pe/{slug}/",
    aboutPath: "/pe/about-us/",
    contactPath: "/pe/contact-us/",
    caseStudyPath: "/pe/case-studies/",
    address: "Lima, Peru",
    phone: "+51 (1) 000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers RM 111-2013-MEM arc flash studies, CNE-aligned compliance, and full power system engineering services across Peru.",
    services: [
      { label: "Arc Flash Study", href: "/pe/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/pe/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/pe/motor-start-analysis/" },
      { label: "Power System Study", href: "/pe/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/pe/power-quality-analysis/" },
    ],
    standards: ["RM 111-2013-MEM", "CNE", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "RM 111-2013-MEM",
    localCodeName: "CNE (Código Nacional de Electricidad)",
    localAuthority: "OSINERGMIN",
  },
  ar: {
    cc: "ar",
    countryName: "Argentina",
    countryNameLocative: "Argentina",
    hreflang: "en-AR",
    dialCodeCountryIso2: "AR",
    servicesIndexPath: "/ar/services/",
    serviceDetailPattern: "/ar/{slug}/",
    blogIndexPath: "/ar/blogs/",
    blogDetailPattern: "/ar/{slug}/",
    aboutPath: "/ar/about-us/",
    contactPath: "/ar/contact-us/",
    caseStudyPath: "/ar/case-studies/",
    address: "Buenos Aires, Argentina",
    phone: "+54 (11) 0000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers AEA 90364 arc flash studies, IRAM 2281 compliance, and full power system engineering services across Argentina.",
    services: [
      { label: "Arc Flash Study", href: "/ar/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/ar/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/ar/motor-start-analysis/" },
      { label: "Power System Study", href: "/ar/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/ar/power-quality-analysis/" },
    ],
    standards: ["AEA 90364", "IRAM 2281", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "AEA 90364",
    localCodeName: "Reglamentación AEA 90364",
    localAuthority: "ENRE",
  },
  cl: {
    cc: "cl",
    countryName: "Chile",
    countryNameLocative: "Chile",
    hreflang: "en-CL",
    dialCodeCountryIso2: "CL",
    servicesIndexPath: "/cl/services/",
    serviceDetailPattern: "/cl/{slug}/",
    blogIndexPath: "/cl/blogs/",
    blogDetailPattern: "/cl/{slug}/",
    aboutPath: "/cl/about-us/",
    contactPath: "/cl/contact-us/",
    caseStudyPath: "/cl/case-studies/",
    address: "Santiago, Chile",
    phone: "+56 (2) 000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers NCh Elec. 4/2003 arc flash studies, SEC-aligned compliance, and full power system engineering services across Chile.",
    services: [
      { label: "Arc Flash Study", href: "/cl/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/cl/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/cl/motor-start-analysis/" },
      { label: "Power System Study", href: "/cl/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/cl/power-quality-analysis/" },
    ],
    standards: ["NCh Elec. 4/2003", "NSEG 5 En. 71", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "NCh Elec. 4/2003",
    localCodeName: "NCh Elec. 4/2003 (Chilean Electrical Code)",
    localAuthority: "SEC (Superintendencia de Electricidad y Combustibles)",
  },
  co: {
    cc: "co",
    countryName: "Colombia",
    countryNameLocative: "Colombia",
    hreflang: "en-CO",
    dialCodeCountryIso2: "CO",
    servicesIndexPath: "/co/services/",
    serviceDetailPattern: "/co/{slug}/",
    blogIndexPath: "/co/blogs/",
    blogDetailPattern: "/co/{slug}/",
    aboutPath: "/co/about-us/",
    contactPath: "/co/contact-us/",
    caseStudyPath: "/co/case-studies/",
    address: "Bogotá, Colombia",
    phone: "+57 (1) 000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers RETIE arc flash studies, NTC 2050 compliance, and full power system engineering services across Colombia.",
    services: [
      { label: "Arc Flash Study", href: "/co/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/co/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/co/motor-start-analysis/" },
      { label: "Power System Study", href: "/co/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/co/power-quality-analysis/" },
    ],
    standards: ["RETIE", "NTC 2050", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "RETIE",
    localCodeName: "NTC 2050 (Colombian Electrical Code)",
    localAuthority: "Ministerio de Minas y Energía",
  },
  br: {
    cc: "br",
    countryName: "Brazil",
    countryNameLocative: "Brazil",
    hreflang: "en-BR",
    dialCodeCountryIso2: "BR",
    servicesIndexPath: "/br/services/",
    serviceDetailPattern: "/br/{slug}/",
    blogIndexPath: "/br/blogs/",
    blogDetailPattern: "/br/{slug}/",
    aboutPath: "/br/about-us/",
    contactPath: "/br/contact-us/",
    caseStudyPath: "/br/case-studies/",
    address: "São Paulo, Brazil",
    phone: "+55 (11) 0000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers NR-10 arc flash studies, ABNT NBR 5410 compliance, and full power system engineering services across Brazil.",
    services: [
      { label: "Arc Flash Study", href: "/br/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/br/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/br/motor-start-analysis/" },
      { label: "Power System Study", href: "/br/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/br/power-quality-analysis/" },
    ],
    standards: [
      "NR-10",
      "ABNT NBR 5410",
      "IEEE 1584",
      "IEC 60909",
      "ISO 9001:2008",
      "IEEE 112-2004",
      "IEC 60034-2-1",
      "ETAP",
    ],
    primaryStandard: "NR-10",
    localCodeName: "ABNT NBR 5410 (Brazilian Electrical Installations)",
    localAuthority: "Ministério do Trabalho",
  },
};
