// Country configuration registry. One entry per live country subdirectory.
// Used by <RegionNavbar>, <RegionFooter>, <RegionMobileNav>, and page metadata.
// Adding a new country:
//   1. Add an entry here
//   2. Create pages in src/app/[cc]/
//   3. Add sitemap + redirect entries in sitemap.ts / next.config.mjs
//
// Do NOT include "us" or "ca" here — those keep their legacy dedicated components
// (us-footer.tsx, sticky-navbar.tsx, ca-footer.tsx, ca-navbar.tsx) for zero regression risk.

export interface CountryNavService {
  label: string;
  href: string;
}

export interface CountryConfig {
  cc: string;                       // "mx", "br", ...
  countryName: string;              // "Mexico"
  countryNameLocative: string;      // "Mexico" for "in Mexico"
  hreflang: string;                 // "en-MX"
  dialCodeCountryIso2: string;      // "MX" (used as contact form default)

  // URL layout (differs per country)
  servicesIndexPath: string;        // "/mx/service/"
  serviceDetailPattern: string;     // "/mx/{slug}/" or "/mx/services/{slug}/"
  blogIndexPath: string;            // "/mx/blogs/" or "/mx/blog/" or "/mx/our-blogs/"
  blogDetailPattern: string;        // "/mx/{slug}/" or "/mx/blog/{slug}/"
  aboutPath: string;                // "/mx/about-us/"
  contactPath: string;              // "/mx/contact-us/"
  caseStudyPath: string | null;     // "/mx/case-study/" or null

  // Footer / contact
  address: string;                  // "Mexico City, Mexico"
  phone: string;                    // "+52 (800) 000-0000"
  email: string;                    // "info@carelabz.com"
  footerDescription: string;        // full sentence

  // Services shown in nav dropdown + footer (label + relative href)
  services: CountryNavService[];

  // Local electrical standards (used in Strapi seoKeywords, trust badges, etc.)
  standards: string[];              // ["NOM-029-STPS-2011", "IEEE 1584", ...]
  primaryStandard: string;          // "NOM-029-STPS-2011"
  localCodeName: string;            // "Mexican Electrical Code (NOM-001-SEDE)"
  localAuthority: string;           // "STPS"
}

// Helper to build standard service list from slugs
function defaultServices(cc: string, pattern: (slug: string) => string): CountryNavService[] {
  return [
    { label: "Arc Flash Study", href: pattern("arc-flash-study") },
    { label: "Short Circuit Analysis", href: pattern("short-circuit-analysis") },
    { label: "Load Flow Analysis", href: pattern("load-flow-analysis") },
    { label: "Relay Coordination Study", href: pattern("relay-coordination-study") },
  ];
}

export const COUNTRY_CONFIGS: Record<string, CountryConfig> = {
  mx: {
    cc: "mx",
    countryName: "Mexico",
    countryNameLocative: "Mexico",
    hreflang: "en-MX",
    dialCodeCountryIso2: "MX",
    servicesIndexPath: "/mx/service/",
    serviceDetailPattern: "/mx/{slug}/",
    blogIndexPath: "/mx/blogs/",
    blogDetailPattern: "/mx/{slug}/",
    aboutPath: "/mx/about-us/",
    contactPath: "/mx/contact-us/",
    caseStudyPath: null,
    address: "Mexico City, Mexico",
    phone: "+52 (55) 0000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers NOM-029 arc flash studies, NOM-001-SEDE compliance, and full power system engineering services across Mexico.",
    services: defaultServices("mx", (s) => `/mx/${s}/`),
    standards: [
      "NOM-029-STPS-2011",
      "NOM-001-SEDE",
      "IEEE 1584",
      "IEC 60909",
      "ETAP",
      "NFPA 70E",
    ],
    primaryStandard: "NOM-029-STPS-2011",
    localCodeName: "Mexican Electrical Code (NOM-001-SEDE)",
    localAuthority: "STPS (Secretaría del Trabajo)",
  },
  at: {
    cc: "at", countryName: "Austria", countryNameLocative: "Austria",
    hreflang: "en-AT", dialCodeCountryIso2: "AT",
    servicesIndexPath: "/at/our-services/", serviceDetailPattern: "/at/{slug}/",
    blogIndexPath: "/at/blogs/", blogDetailPattern: "/at/{slug}/",
    aboutPath: "/at/about-us/", contactPath: "/at/contact-us/", caseStudyPath: null,
    address: "Vienna, Austria", phone: "+43 0 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers ÖVE/ÖNORM E 8001 arc flash studies, AUVA-aligned compliance, and full power system engineering services across Austria.",
    services: [
      { label: "Arc Flash Study", href: "/at/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/at/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/at/motor-start-analysis/" },
      { label: "Power System Study", href: "/at/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/at/power-quality-analysis/" },
    ],
    standards: ["ÖVE/ÖNORM E 8001", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "ÖVE/ÖNORM E 8001",
    localCodeName: "ÖVE/ÖNORM E 8001 (Austrian Electrical Installation Standard)",
    localAuthority: "AUVA",
  },
  ch: {
    cc: "ch", countryName: "Switzerland", countryNameLocative: "Switzerland",
    hreflang: "en-CH", dialCodeCountryIso2: "CH",
    servicesIndexPath: "/ch/our-services/", serviceDetailPattern: "/ch/{slug}/",
    blogIndexPath: "/ch/blogs/", blogDetailPattern: "/ch/{slug}/",
    aboutPath: "/ch/about-us/", contactPath: "/ch/contact-us/", caseStudyPath: null,
    address: "Zurich, Switzerland", phone: "+41 00 000 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers NIN arc flash studies, SUVA-aligned compliance, and full power system engineering services across Switzerland.",
    services: [
      { label: "Arc Flash Study", href: "/ch/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/ch/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/ch/motor-start-analysis/" },
      { label: "Power System Study", href: "/ch/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/ch/power-quality-analysis/" },
    ],
    standards: ["NIN (SEV 1000)", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "NIN (SEV 1000)",
    localCodeName: "NIN — Niederspannungs-Installationsnorm",
    localAuthority: "SUVA",
  },
  be: {
    cc: "be", countryName: "Belgium", countryNameLocative: "Belgium",
    hreflang: "en-BE", dialCodeCountryIso2: "BE",
    servicesIndexPath: "/be/our-services/", serviceDetailPattern: "/be/{slug}/",
    blogIndexPath: "/be/blogs/", blogDetailPattern: "/be/{slug}/",
    aboutPath: "/be/about-us/", contactPath: "/be/contact-us/", caseStudyPath: null,
    address: "Brussels, Belgium", phone: "+32 0 000 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers AREI/RGIE arc flash studies, FPS Economy-aligned compliance, and full power system engineering services across Belgium.",
    services: [
      { label: "Arc Flash Study", href: "/be/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/be/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/be/motor-start-analysis/" },
      { label: "Power System Study", href: "/be/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/be/power-quality-analysis/" },
    ],
    standards: ["AREI/RGIE", "NBN HD 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "AREI/RGIE",
    localCodeName: "AREI/RGIE (Belgian Electrical Installation Regulation)",
    localAuthority: "FPS Economy",
  },
  nl: {
    cc: "nl", countryName: "Netherlands", countryNameLocative: "the Netherlands",
    hreflang: "en-NL", dialCodeCountryIso2: "NL",
    servicesIndexPath: "/nl/our-services/", serviceDetailPattern: "/nl/{slug}/",
    blogIndexPath: "/nl/blogs/", blogDetailPattern: "/nl/{slug}/",
    aboutPath: "/nl/about-us/", contactPath: "/nl/contact-us/", caseStudyPath: null,
    address: "Amsterdam, Netherlands", phone: "+31 00 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers NEN 1010 arc flash studies, ISZW-aligned compliance, and full power system engineering services across the Netherlands.",
    services: [
      { label: "Arc Flash Study", href: "/nl/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/nl/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/nl/motor-start-analysis/" },
      { label: "Power System Study", href: "/nl/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/nl/power-quality-analysis/" },
    ],
    standards: ["NEN 1010", "NEN 3140", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "NEN 1010",
    localCodeName: "NEN 1010 (Dutch Electrical Installation Standard)",
    localAuthority: "ISZW",
  },
  de: {
    cc: "de", countryName: "Germany", countryNameLocative: "Germany",
    hreflang: "en-DE", dialCodeCountryIso2: "DE",
    servicesIndexPath: "/de/services/", serviceDetailPattern: "/de/services/{slug}/",
    blogIndexPath: "/de/blogs/", blogDetailPattern: "/de/{slug}/",
    aboutPath: "/de/about-us/", contactPath: "/de/contact-us/", caseStudyPath: null,
    address: "Berlin, Germany", phone: "+49 00 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers VDE 0100 arc flash studies, BAuA-aligned compliance, and full power system engineering services across Germany.",
    services: [
      { label: "Arc Flash Study", href: "/de/services/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/de/services/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/de/services/motor-start-analysis/" },
      { label: "Power System Study", href: "/de/services/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/de/services/power-quality-analysis/" },
    ],
    standards: ["DIN VDE 0100", "DIN VDE 0105", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "DIN VDE 0100",
    localCodeName: "DIN VDE 0100 (German Electrical Installation Standard)",
    localAuthority: "BAuA",
  },
  fr: {
    cc: "fr", countryName: "France", countryNameLocative: "France",
    hreflang: "en-FR", dialCodeCountryIso2: "FR",
    servicesIndexPath: "/fr/our-services/", serviceDetailPattern: "/fr/{slug}/",
    blogIndexPath: "/fr/blogs/", blogDetailPattern: "/fr/{slug}/",
    aboutPath: "/fr/about-us/", contactPath: "/fr/contact-us/", caseStudyPath: null,
    address: "Paris, France", phone: "+33 0 00 00 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers NF C 15-100 arc flash studies, INRS-aligned compliance, and full power system engineering services across France.",
    services: [
      { label: "Arc Flash Study", href: "/fr/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/fr/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/fr/motor-start-analysis/" },
      { label: "Power System Study", href: "/fr/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/fr/power-quality-analysis/" },
    ],
    standards: ["NF C 15-100", "NF C 18-510", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "NF C 15-100",
    localCodeName: "NF C 15-100 (French Electrical Installation Standard)",
    localAuthority: "INRS",
  },
  gr: {
    cc: "gr", countryName: "Greece", countryNameLocative: "Greece",
    hreflang: "en-GR", dialCodeCountryIso2: "GR",
    servicesIndexPath: "/gr/our-services/", serviceDetailPattern: "/gr/{slug}/",
    blogIndexPath: "/gr/blogs/", blogDetailPattern: "/gr/{slug}/",
    aboutPath: "/gr/about-us/", contactPath: "/gr/contact-us/", caseStudyPath: null,
    address: "Athens, Greece", phone: "+30 000 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers ELOT HD 384 arc flash studies, local authority-aligned compliance, and full power system engineering services across Greece.",
    services: [
      { label: "Arc Flash Study", href: "/gr/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/gr/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/gr/motor-start-analysis/" },
      { label: "Power System Study", href: "/gr/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/gr/power-quality-analysis/" },
    ],
    standards: ["ELOT HD 384", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "ELOT HD 384",
    localCodeName: "ELOT HD 384 (Greek Electrical Installation Standard)",
    localAuthority: "Ministry of Environment and Energy",
  },
  pt: {
    cc: "pt", countryName: "Portugal", countryNameLocative: "Portugal",
    hreflang: "en-PT", dialCodeCountryIso2: "PT",
    servicesIndexPath: "/pt/our-services/", serviceDetailPattern: "/pt/{slug}/",
    blogIndexPath: "/pt/blogs/", blogDetailPattern: "/pt/{slug}/",
    aboutPath: "/pt/about-us/", contactPath: "/pt/contact-us/", caseStudyPath: null,
    address: "Lisbon, Portugal", phone: "+351 000 000 000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers RTIEBT arc flash studies, ACT-aligned compliance, and full power system engineering services across Portugal.",
    services: [
      { label: "Arc Flash Study", href: "/pt/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/pt/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/pt/motor-start-analysis/" },
      { label: "Power System Study", href: "/pt/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/pt/power-quality-analysis/" },
    ],
    standards: ["RTIEBT", "NP HD 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "RTIEBT",
    localCodeName: "RTIEBT (Portuguese Electrical Installation Regulations)",
    localAuthority: "ACT",
  },
  es: {
    cc: "es", countryName: "Spain", countryNameLocative: "Spain",
    hreflang: "en-ES", dialCodeCountryIso2: "ES",
    servicesIndexPath: "/es/our-services/", serviceDetailPattern: "/es/{slug}/",
    blogIndexPath: "/es/blogs/", blogDetailPattern: "/es/{slug}/",
    aboutPath: "/es/about-us/", contactPath: "/es/contact-us/", caseStudyPath: null,
    address: "Madrid, Spain", phone: "+34 00 000 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers REBT arc flash studies, INSST-aligned compliance, and full power system engineering services across Spain.",
    services: [
      { label: "Arc Flash Study", href: "/es/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/es/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/es/motor-start-analysis/" },
      { label: "Power System Study", href: "/es/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/es/power-quality-analysis/" },
    ],
    standards: ["REBT", "RD 614/2001", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "REBT",
    localCodeName: "REBT (Reglamento Electrotécnico para Baja Tensión)",
    localAuthority: "INSST",
  },
  it: {
    cc: "it", countryName: "Italy", countryNameLocative: "Italy",
    hreflang: "en-IT", dialCodeCountryIso2: "IT",
    servicesIndexPath: "/it/our-services/", serviceDetailPattern: "/it/{slug}/",
    blogIndexPath: "/it/blogs/", blogDetailPattern: "/it/{slug}/",
    aboutPath: "/it/about-us/", contactPath: "/it/contact-us/", caseStudyPath: null,
    address: "Milan, Italy", phone: "+39 00 0000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers CEI 64-8 arc flash studies, INAIL-aligned compliance, and full power system engineering services across Italy.",
    services: [
      { label: "Arc Flash Study", href: "/it/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/it/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/it/motor-start-analysis/" },
      { label: "Power System Study", href: "/it/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/it/power-quality-analysis/" },
    ],
    standards: ["CEI 64-8", "D.Lgs 81/2008", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "CEI 64-8",
    localCodeName: "CEI 64-8 (Italian Electrical Installation Standard)",
    localAuthority: "INAIL",
  },
  fi: {
    cc: "fi", countryName: "Finland", countryNameLocative: "Finland",
    hreflang: "en-FI", dialCodeCountryIso2: "FI",
    servicesIndexPath: "/fi/our-services/", serviceDetailPattern: "/fi/{slug}/",
    blogIndexPath: "/fi/blogs/", blogDetailPattern: "/fi/{slug}/",
    aboutPath: "/fi/about-us/", contactPath: "/fi/contact-us/", caseStudyPath: null,
    address: "Helsinki, Finland", phone: "+358 00 000 0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers SFS 6000 arc flash studies, Tukes-aligned compliance, and full power system engineering services across Finland.",
    services: [
      { label: "Arc Flash Study", href: "/fi/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/fi/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/fi/motor-start-analysis/" },
      { label: "Power System Study", href: "/fi/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/fi/power-quality-analysis/" },
    ],
    standards: ["SFS 6000", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "SFS 6000",
    localCodeName: "SFS 6000 (Finnish Electrical Installation Standard)",
    localAuthority: "Tukes",
  },
  dk: {
    cc: "dk", countryName: "Denmark", countryNameLocative: "Denmark",
    hreflang: "en-DK", dialCodeCountryIso2: "DK",
    servicesIndexPath: "/dk/our-services/", serviceDetailPattern: "/dk/{slug}/",
    blogIndexPath: "/dk/blogs/", blogDetailPattern: "/dk/{slug}/",
    aboutPath: "/dk/about-us/", contactPath: "/dk/contact-us/", caseStudyPath: null,
    address: "Copenhagen, Denmark", phone: "+45 00 00 00 00", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers DS/HD 60364 arc flash studies, Sikkerhedsstyrelsen compliance, and full power system engineering services across Denmark.",
    services: [
      { label: "Arc Flash Study", href: "/dk/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/dk/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/dk/motor-start-analysis/" },
      { label: "Power System Study", href: "/dk/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/dk/power-quality-analysis/" },
    ],
    standards: ["DS/HD 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "DS/HD 60364",
    localCodeName: "DS/HD 60364 (Danish Electrical Installation Standard)",
    localAuthority: "Sikkerhedsstyrelsen",
  },
  no: {
    cc: "no", countryName: "Norway", countryNameLocative: "Norway",
    hreflang: "en-NO", dialCodeCountryIso2: "NO",
    servicesIndexPath: "/no/our-services/", serviceDetailPattern: "/no/{slug}/",
    blogIndexPath: "/no/blogs/", blogDetailPattern: "/no/{slug}/",
    aboutPath: "/no/about-us/", contactPath: "/no/contact-us/", caseStudyPath: null,
    address: "Oslo, Norway", phone: "+47 000 00 000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers NEK 400 arc flash studies, DSB-aligned compliance, and full power system engineering services across Norway.",
    services: [
      { label: "Arc Flash Study", href: "/no/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/no/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/no/motor-start-analysis/" },
      { label: "Power System Study", href: "/no/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/no/power-quality-analysis/" },
    ],
    standards: ["NEK 400", "FEK", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "NEK 400",
    localCodeName: "NEK 400 (Norwegian Electrical Installation Standard)",
    localAuthority: "DSB (Direktoratet for samfunnssikkerhet)",
  },
  se: {
    cc: "se", countryName: "Sweden", countryNameLocative: "Sweden",
    hreflang: "en-SE", dialCodeCountryIso2: "SE",
    servicesIndexPath: "/se/our-services/", serviceDetailPattern: "/se/{slug}/",
    blogIndexPath: "/se/blogs/", blogDetailPattern: "/se/{slug}/",
    aboutPath: "/se/about-us/", contactPath: "/se/contact-us/", caseStudyPath: null,
    address: "Stockholm, Sweden", phone: "+46 (8) 000-0000", email: "info@carelabz.com",
    footerDescription: "Carelabs delivers EBR-aligned arc flash studies, Elsäkerhetsverket-compliant power system engineering across Sweden.",
    services: [
      { label: "Arc Flash Study", href: "/se/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/se/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/se/motor-start-analysis/" },
      { label: "Power System Study", href: "/se/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/se/power-quality-analysis/" },
    ],
    standards: ["EBR 18:2017", "SS-EN 60364", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "EBR 18:2017",
    localCodeName: "SS-EN 60364 (Swedish Electrical Installation Standard)",
    localAuthority: "Elsäkerhetsverket",
  },
  ie: {
    cc: "ie",
    countryName: "Ireland",
    countryNameLocative: "Ireland",
    hreflang: "en-IE",
    dialCodeCountryIso2: "IE",
    servicesIndexPath: "/ie/our-services/",
    serviceDetailPattern: "/ie/{slug}/",
    blogIndexPath: "/ie/blogs/",
    blogDetailPattern: "/ie/{slug}/",
    aboutPath: "/ie/about-us/",
    contactPath: "/ie/contact-us/",
    caseStudyPath: null,
    address: "Dublin, Ireland",
    phone: "+353 (1) 000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers I.S. 10101 arc flash studies, HSA-aligned compliance, and full power system engineering services across Ireland.",
    services: [
      { label: "Arc Flash Study", href: "/ie/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/ie/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/ie/motor-start-analysis/" },
      { label: "Power System Study", href: "/ie/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/ie/power-quality-analysis/" },
    ],
    standards: ["I.S. 10101:2020", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "I.S. 10101:2020",
    localCodeName: "I.S. 10101 (Irish National Electrical Safety Standard)",
    localAuthority: "HSA (Health and Safety Authority)",
  },
  uk: {
    cc: "uk",
    countryName: "United Kingdom",
    countryNameLocative: "the UK",
    hreflang: "en-GB",
    dialCodeCountryIso2: "GB",
    servicesIndexPath: "/uk/our-services/",
    serviceDetailPattern: "/uk/{slug}/",
    blogIndexPath: "/uk/blogs/",
    blogDetailPattern: "/uk/{slug}/",
    aboutPath: "/uk/about-us/",
    contactPath: "/uk/contact-us/",
    caseStudyPath: null,
    address: "London, United Kingdom",
    phone: "+44 (20) 0000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers BS 7671 arc flash studies, IET Wiring Regulations compliance, and full power system engineering services across the UK.",
    services: [
      { label: "Arc Flash Study", href: "/uk/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/uk/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/uk/motor-start-analysis/" },
      { label: "Power System Study", href: "/uk/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/uk/power-quality-analysis/" },
    ],
    standards: ["BS 7671", "IET Wiring Regulations", "HSR25", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "BS 7671",
    localCodeName: "BS 7671 / IET Wiring Regulations",
    localAuthority: "HSE (Health and Safety Executive)",
  },
  pe: {
    cc: "pe",
    countryName: "Peru",
    countryNameLocative: "Peru",
    hreflang: "en-PE",
    dialCodeCountryIso2: "PE",
    servicesIndexPath: "/pe/services/",
    serviceDetailPattern: "/pe/{slug}/",
    blogIndexPath: "/pe/blogs/",
    blogDetailPattern: "/pe/{slug}/",
    aboutPath: "/pe/about-us/",
    contactPath: "/pe/contact-us/",
    caseStudyPath: null,
    address: "Lima, Peru",
    phone: "+51 (1) 000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers RM 111-2013-MEM arc flash studies, CNE-aligned compliance, and full power system engineering services across Peru.",
    services: [
      { label: "Arc Flash Study", href: "/pe/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/pe/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/pe/motor-start-analysis/" },
      { label: "Power System Study", href: "/pe/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/pe/power-quality-analysis/" },
    ],
    standards: ["RM 111-2013-MEM", "CNE", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "RM 111-2013-MEM",
    localCodeName: "CNE (Código Nacional de Electricidad)",
    localAuthority: "OSINERGMIN",
  },
  ar: {
    cc: "ar",
    countryName: "Argentina",
    countryNameLocative: "Argentina",
    hreflang: "en-AR",
    dialCodeCountryIso2: "AR",
    servicesIndexPath: "/ar/services/",
    serviceDetailPattern: "/ar/{slug}/",
    blogIndexPath: "/ar/blogs/",
    blogDetailPattern: "/ar/{slug}/",
    aboutPath: "/ar/about-us/",
    contactPath: "/ar/contact-us/",
    caseStudyPath: null,
    address: "Buenos Aires, Argentina",
    phone: "+54 (11) 0000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers AEA 90364 arc flash studies, IRAM 2281 compliance, and full power system engineering services across Argentina.",
    services: [
      { label: "Arc Flash Study", href: "/ar/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/ar/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/ar/motor-start-analysis/" },
      { label: "Power System Study", href: "/ar/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/ar/power-quality-analysis/" },
    ],
    standards: ["AEA 90364", "IRAM 2281", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "AEA 90364",
    localCodeName: "Reglamentación AEA 90364",
    localAuthority: "ENRE",
  },
  cl: {
    cc: "cl",
    countryName: "Chile",
    countryNameLocative: "Chile",
    hreflang: "en-CL",
    dialCodeCountryIso2: "CL",
    servicesIndexPath: "/cl/services/",
    serviceDetailPattern: "/cl/{slug}/",
    blogIndexPath: "/cl/blogs/",
    blogDetailPattern: "/cl/{slug}/",
    aboutPath: "/cl/about-us/",
    contactPath: "/cl/contact-us/",
    caseStudyPath: null,
    address: "Santiago, Chile",
    phone: "+56 (2) 000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers NCh Elec. 4/2003 arc flash studies, SEC-aligned compliance, and full power system engineering services across Chile.",
    services: [
      { label: "Arc Flash Study", href: "/cl/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/cl/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/cl/motor-start-analysis/" },
      { label: "Power System Study", href: "/cl/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/cl/power-quality-analysis/" },
    ],
    standards: ["NCh Elec. 4/2003", "NSEG 5 En. 71", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "NCh Elec. 4/2003",
    localCodeName: "NCh Elec. 4/2003 (Chilean Electrical Code)",
    localAuthority: "SEC (Superintendencia de Electricidad y Combustibles)",
  },
  co: {
    cc: "co",
    countryName: "Colombia",
    countryNameLocative: "Colombia",
    hreflang: "en-CO",
    dialCodeCountryIso2: "CO",
    servicesIndexPath: "/co/services/",
    serviceDetailPattern: "/co/{slug}/",
    blogIndexPath: "/co/blogs/",
    blogDetailPattern: "/co/{slug}/",
    aboutPath: "/co/about-us/",
    contactPath: "/co/contact-us/",
    caseStudyPath: null,
    address: "Bogotá, Colombia",
    phone: "+57 (1) 000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers RETIE arc flash studies, NTC 2050 compliance, and full power system engineering services across Colombia.",
    services: [
      { label: "Arc Flash Study", href: "/co/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/co/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/co/motor-start-analysis/" },
      { label: "Power System Study", href: "/co/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/co/power-quality-analysis/" },
    ],
    standards: ["RETIE", "NTC 2050", "IEEE 1584", "IEC 60909", "ETAP"],
    primaryStandard: "RETIE",
    localCodeName: "NTC 2050 (Colombian Electrical Code)",
    localAuthority: "Ministerio de Minas y Energía",
  },
  br: {
    cc: "br",
    countryName: "Brazil",
    countryNameLocative: "Brazil",
    hreflang: "en-BR",
    dialCodeCountryIso2: "BR",
    servicesIndexPath: "/br/services/",
    serviceDetailPattern: "/br/{slug}/",
    blogIndexPath: "/br/blogs/",
    blogDetailPattern: "/br/{slug}/",
    aboutPath: "/br/about-us/",
    contactPath: "/br/contact-us/",
    caseStudyPath: null,
    address: "São Paulo, Brazil",
    phone: "+55 (11) 0000-0000",
    email: "info@carelabz.com",
    footerDescription:
      "Carelabs delivers NR-10 arc flash studies, ABNT NBR 5410 compliance, and full power system engineering services across Brazil.",
    services: [
      { label: "Arc Flash Study", href: "/br/arc-flash-study/" },
      { label: "Harmonic Study & Analysis", href: "/br/harmonic-study-and-analysis/" },
      { label: "Motor Start Analysis", href: "/br/motor-start-analysis/" },
      { label: "Power System Study", href: "/br/power-system-study-and-analysis/" },
      { label: "Power Quality Analysis", href: "/br/power-quality-analysis/" },
    ],
    standards: [
      "NR-10",
      "ABNT NBR 5410",
      "IEEE 1584",
      "IEC 60909",
      "ETAP",
    ],
    primaryStandard: "NR-10",
    localCodeName: "ABNT NBR 5410 (Brazilian Electrical Installations)",
    localAuthority: "Ministério do Trabalho",
  },
};
